-- Sales Street Kit - Supabase Schema
-- Run this in Supabase SQL Editor to create the places table

create table public.places (
  id bigint generated by default as identity primary key,
  layer text not null check (layer in ('toilets','freespace','charging','premium')),
  name text not null,
  district text,
  type text not null default 'free' check (type in ('free','paid')),
  hours text,
  wifi boolean default false,
  power boolean default false,
  rating double precision,
  note text,
  lat double precision not null,
  lng double precision not null,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.places enable row level security;

-- Policy: Anyone can read approved places
create policy "read approved" on public.places
  for select using (approved = true);

-- Policy: Anyone can insert (but must be unapproved)
create policy "insert pending" on public.places
  for insert with check (approved = false);
